# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-01 14:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20171126_1108'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='image',
            field=models.TextField(blank=True, null=True),
        ),
    ]
